### ISSUE TITLE
wrong enrollment

### ISSUE THREAD

**Issue by Filippo73** [ewallah/moodle-enrol_coursecompleted#10]
Hi,
I created a course and I described as completion criteria having finished 4 activities AND having a minimum score of 60 points in the final test (it is a four-step test).
According to the logic of completion only users who have both the requirements complete the course.
I created a second course and as enrollmnet methods I chose the completion of the first course.
Everything works fine for users who accomplish both the criteria. What is really odd is that in the second course are enrolled users who shouldn't be enrolled too (they didn't reach the minimum score).
I attach:
- the completion criteria of the first course;
- the results of the firts course (starting course)
- the enrollment methods of the second course
- the list of enrolled users in the second course
- the details of enrollment of the user 1
- the details of enrollment of the user 2

If you look at the results of the starting course you can see that it is really odd: the first user shouldn't be enrolled in the second course but he is. The second user with the same problem (he didn't reach the minimum score) isn't enrolled in the scond course.
Thank you.
Fil

![details_user_2](https://user-images.githubusercontent.com/44192400/59344113-b1e24c80-8d0d-11e9-8df9-79205db04f1e.jpg)
![details_user_1](https://user-images.githubusercontent.com/44192400/59344142-c3c3ef80-8d0d-11e9-9125-0e5fe2e33e29.jpg)
![list_of_enrolled_users](https://user-images.githubusercontent.com/44192400/59344046-852e3500-8d0d-11e9-9460-df491d5ed680.jpg)
![completion_criteria_course_1](https://user-images.githubusercontent.com/44192400/59343925-2f598d00-8d0d-11e9-91f9-795d51014cc7.jpg)
![results_of_starting_course](https://user-images.githubusercontent.com/44192400/59343987-53b56980-8d0d-11e9-9eb8-0341119f1553.jpg)
![enrollment_methods](https://user-images.githubusercontent.com/44192400/59344029-78114600-8d0d-11e9-901e-16668e46aebc.jpg)

**Comment by ewallah** [comment]
Hi Filippo,

THX for your screenshots, However, I still need a screenshot of the course completion report (report/completion/index.php?course=???) to be sure this is not related to incorrect grading settings (cfr https://moodle.org/mod/forum/discuss.php?d=194747).
![Completion_report](https://user-images.githubusercontent.com/1324161/59358310-9b97b900-8d2c-11e9-9cf1-71b8e5716f9e.png)

**Comment by ewallah** [comment]
This problem seems to be related with course completion and not with enrollment.
