### ISSUE TITLE
Question / Feature Request: Enrol to different courses based on cohort membership

### ISSUE THREAD

**Issue by amenk** [ewallah/moodle-enrol_coursecompleted#13]
We have different user cohorts, for example Cohort 1 and Cohort 2 

They have to to all courses 1 - 5 sequentially, this would be possible with your plugin.

But after that there are deepening courses so that Cohort 1 has to continue with 7 and Cohort 2 with 6 and so on.

We have around 10 groups and 10 deepening courses.

We think about using your module as a basis for our implementation: Allow in auto enroll to specify one or more cohorts for which the auto enrollment should be triggered.

Woudl that be in scope of the module? Would such a PR be merged? Do you have any hints where to start that?

**Comment by amenk** [comment]
Would it be enough to add a if condition to https://github.com/ewallah/moodle-enrol_coursecompleted/blob/master/classes/observer.php#L47 and a database field to let us specify the cohort filter on the auto-enrol definition

**Comment by ewallah** [comment]
Hello Alexander,

adding an extra level to complexity to this plugin is perhaps not the right track. In the user fora I see that a lot of people not even understand the concept of course completion. Before we know it people will ask to add a date, language, grouping or custom field to this condition.

But this plugin should not only work with 10 courses but also with 1000 courses, 10 cohorts but also with 1000 cohorts. And here I see possible performance issues when one starts combining parameters.

In your specific case, I would use this plugin in course 1-5, but add a local plugin that takes care of this automatic group enrollment on course completion of course 5. This solves your problem - is far less complex - and can be a good sample for other people who want to use groupings or custom fields as an extra parameter.

As this is open source, you can copy most code from this plugin and add the group logic to this local plugin.

**Comment by amenk** [comment]
Okay, thanks. This perfectly makes sense.

In the end of the day, we might need large portions of your module, and add only a few lines.

Might it be possible to add some extension points? Like extracting some code to protected methods so we can overwrite it.

Of course we can also just fork the module on GitHub and modify it, but that might not be the most sustainable solution ?

Let us know what you think :)

**Comment by amenk** [comment]
I will just fork it... https://github.com/iMi-digital/moodle-enrol_coursecompleted
