### ISSUE TITLE
Fails to enrol users (doesn't account for deleted users?)

### ISSUE THREAD

**Issue by jackawardls** [ewallah/moodle-enrol_coursecompleted#23]
I think I have encountered a bug.

I receive this error when I try to enrol users:
![Coding error detected, User ID does not exist or is deleted!](https://i.imgur.com/2CoprXI.png)

I think this may be happening because the plugin is trying to enrol users who are marked as deleted in the database.

**Comment by ewallah** [comment]
THX for the report.

Indeed, currently the bulk enrolment method is not checking is a user is deleted or not. So I will modify the query to select all possible candidates to exclude deleted users.

**Comment by jackawardls** [comment]
> 
> 
> THX for the report.
> 
> Indeed, currently the bulk enrolment method is not checking is a user is deleted or not. So I will modify the query to select all possible candidates to exclude deleted users.

Thank you! This is greatly appreciated.

**Comment by ewallah** [comment]
Fixed in version 2021053000.
