### ISSUE TITLE
Issues after installing auto group

### ISSUE THREAD

**Issue by vinaypri** [ewallah/moodle-enrol_coursecompleted#26]
We had this plugin working fine until we installed an auto-group plugin as we wanted users to be enrolled into specific groups when auto enrolled to a course. Note that sometimes these groups would not exist and therefore it is required to have these groups created. Course completion enrolment plugin seems to only work with groups that exist.

However after installing the auto group plugin, the course completion enrolment plugin does not auto enrol but shows the eligible users in a + sign against enrolment methods of the course. We also uninstalled both plugins and tried with course enrolment plugin alone  but get the same behaviour.

Any reasons/suggestions to enrol automatically?
Our Moodle version is 3.11+ (Build: 20210701) and Auto group plugin is from https://moodle.org/plugins/local_autogroup version used is 2.5 (2020072700)

**Comment by iplusacademy** [comment]
This seems unrelated to the local_autogroup plugin.

I ran [PHPUnit and Behat tests](https://github.com/ewallah/moodle-enrol_coursecompleted/runs/3789199509?check_suite_focus=true#step:19:116) to see the behaviour of this plugin when the [local_autogroup was installed](https://github.com/ewallah/moodle-enrol_coursecompleted/runs/3789199509?check_suite_focus=true#step:6:1), and all tests passed.  Only the privacy related test failed as the local_autogroup plugin is not GDPR compatible.

So in a test environment this plugin works fine with a non configured local_autogroup plugin.

**Comment by vinaypri** [comment]
Hi Reenat,

I have 2 courses course 1 (name - Class_10_sub_chapter_name) and course 2 (name - chk_grp_1). As you can see, I have configured course 2 to be enrolled on course 1 completion. However a user who is freshly enrolled in course 1 and completes it is not automatically enrolled into course 2. Instead if you see in the enrolment methods in course 2, a + sign appears against the course completion enrolment plugin. Clicking on it shows the users who can be enrolled and expects us to confirm their enrolment. Hope it is clear what I mean by the + sign. Please let me know the conditions in which it does not add automatically other than users who have completed course 1 in the past
![enrolmentmethod-course2](https://user-images.githubusercontent.com/63767689/136150076-0d8eb587-605c-4294-acfc-10a922b98334.png)
![eligibleusers-course2](https://user-images.githubusercontent.com/63767689/136150082-37c99736-3c9c-42ef-b8b4-e94df225a159.png)
![participant-course2](https://user-images.githubusercontent.com/63767689/136150084-c9478c3c-ce8c-4deb-85e0-6b9784fe56d3.png)

**Comment by ewallah** [comment]
Hello Vinaypri,

this is default behavior:  this plugin is not called "enrolment on passed course completions" but "enrolment on course completion". So the moment a course is completed, an event is fired where multiple services can react upon:  a badge can be generated, a certificate can be sent or a log entry is created.  In this case a user is also enrolled into a new course. 

Test user 1 and test user 13 completed the course in the past, before the enrolment method was (re)installed or enabled. People are not enrolled into a new course after comparing a list of users who completed the course with a list of users who are already enrolled, but 1 cron job after they complete the course. This is the reason why people who completed the course in the past are not automatically enrolled, and they have to be added manually using the + sign.

Of course, one can write a simple [CLI script](https://docs.moodle.org/dev/CLI_scripts) to add all users who completed one or all courses in the past.
