### ISSUE TITLE
Add placeholder for course link

### ISSUE THREAD

**Issue by rmeske** [ewallah/moodle-enrol_coursecompleted#27]
Hello,

My apologies, I created a pull request prior to creating this issue.  The use case for including the course link in the email is that, the user is automatically enrolled in a course that they may not know about once they have completed a different course.  We have found this causes some confusion if we do not send an email informing the user they have been enrolled into a course.  Including the link in the email increases the percentage of users that launch the course after being enrolled.

I have made the necessary changes to add this additional placeholder, and am hoping you agree to it's value and will incorporate it.

Regards,
Ron

**Comment by rmeske** [comment]
After reviewing the code in more detail, I have found that additional work is needed to be able to include a course link in the welcome email.  I am open to helping with this if you are open to including this placeholder.

**Comment by ewallah** [comment]
Hello @rmeske,

THX for the feedback!

I did not see your pull request, but I tried some changes in the [dev branch ](https://github.com/ewallah/moodle-enrol_coursecompleted/commit/2302fa321b4a4daf31c066662adc72d2fef9c910).

R

**Comment by ewallah** [comment]
Hello @rmeske,

the customwelcome help displays:

A custom welcome message may be added as plain text or Moodle-auto format, including HTML tags and multi-lang tags.
The following placeholders may be included in the message:
* Course name {$a->coursename}
* Completed course name {$a->completed}
* Link to user's profile page {$a->profileurl}
* User email {$a->email}
* User fullname {$a->fullname}

v3.9.2 added url links to the Course name and the Completed course name.  So I presume this issue can be closed?

R

**Comment by rmeske** [comment]
Hello @ewallah,

How do you insert the link?  Can the URL be added to the email as text so that the user can copy and paste if needed?

Ron

**Comment by ewallah** [comment]
See the documentation of [self enrollment](https://docs.moodle.org/311/en/Self_enrolment#Sending_a_welcome_message_to_new_users).

_Welcome to {coursename}
If you have not done so already, you should edit your profile page so that we can learn more about you: {profilleurl}.
You were enrolled in this course because you completed {completed} ...._

The urls are created automatically.

**Comment by ewallah** [comment]
Fixed in v3.9.2.
