### ISSUE TITLE
Unable to upgrade to v3.9.5 (and up) on Moodle 3.9 due to a MDL-72324

### ISSUE THREAD

**Issue by ctam** [ewallah/moodle-enrol_coursecompleted#32]
The addition of this [code](https://github.com/ewallah/moodle-enrol_coursecompleted/blob/324b432b678d28bb4476221dc15455347571912c/version.php#L31), making this plugin encounter this [Moodle bug](https://tracker.moodle.org/browse/MDL-72324).

**Comment by ewallah** [comment]
Hello @ctam,

THX for the report.

Is this not a false positive?  Because there is a higher version available in the plugin database that does not use $plugin->incompatible, I assume the version with this line will be never installed. Am I wrong?

**Comment by ewallah** [comment]
No feedback, and the support for 3.9 ended on 10 May 2021.

**Comment by ctam** [comment]
We have a site that is still on Moodle 3.9, and I believe the last compatible version of this plugin is v3.9.6, which still has `$plugin->incompatible` in its `version.php` file.  Security support for Moodle 3.9 will end on 11 December 2023.  So, it's reasonable that some sites are still running with it.  I applied this [patch](https://github.com/moodle/moodle/commit/3a33d0571024f17adbf366a36171dd759025b7f2) to the site and it solved the issue.  So, we are good.  Thanks for looking at this.
