### ISSUE TITLE
Breaking changes in the repo

### ISSUE THREAD

**Issue by jwalits** [ewallah/moodle-enrol_coursecompleted#34]
Hi,

We use git submodules to install plugin to our Moodle sites. We have noticed a recent change (probably from early Aug) breaks our codebases completely. 

This is because the following commit is no longer on the main branch (nor its on any branch): https://github.com/ewallah/moodle-enrol_coursecompleted/commit/9171a97ba98b3a08bec0136845695cc66d5bf890

Moodle 3.9 is still in security support till the end of this year (11 Dec). We have clients still on this LTS and when trying to get the latest security releases out to their sites, this repo breaks our CI/CD process.

We cannot use an older commit in the main branch due to this: https://github.com/ewallah/moodle-enrol_coursecompleted/commit/584b5905f69ef1f6fee3cb3cf47db1447835d4ff - it jumps from v3.9.3 to v4.0.0. Our site is currently on v3.9.4, so cannot downgrade to 3.9.3 nor upgrade to 4.0.0 due to version incompatibility.

The way we support this in our plugins is by creating a MOODLE_39_STABLE branch so the older Moodles which are still in the process of upgrading from 3.9 to 4.1 can still checkout the latest supported code. Would this be possible to create a MOODLE_39_STABLE branch in this repo so our CI/CD tools can successfully clone the repo as a submodule?

**Comment by ewallah** [comment]
Hi @jwalits,

THX for your report.

PHP 7.3 died on 18 Nov 2021
PHP 7.4 died on 3 Nov 2022

We do everything so users do NOT run insecure code. Creating a special branch to run only in a insecure environment will never be on our priority list.

I created a MOODLE_39_STABLE branch and all[ Behat tests fail,](https://github.com/ewallah/moodle-enrol_coursecompleted/actions/runs/6009941356/job/16300352464) but everything else passes. So probably this branch can be used for 39+ branches.

**Comment by jwalits** [comment]
Thank you for the prompt feedback and action @ewallah, we will test it out here.

Whilst its true that PHP 7.4 is out of community support, Canonical is still supporting it in the Ubuntu 20.04 base images with regular security updates. The End of standard support for 20.04 is Apr 2025. This is what we use as the base when building our containers for our Moodle sites.

We are in the middle of getting all sites upgraded to 4.1 - but every client has different schedules for when they want to upgrade. As we get closer to end of year, we are hoping we'll not have anyone on 3.9 after Dec '23. Thank you once again for the quick action. Appreciate it greatly.
