### ISSUE TITLE
Increase course list drop down in Moodle plugin.

### ISSUE THREAD

**Issue by maxmail** [ewallah/moodle-enrol_coursecompleted#36]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Describe the bug
The course dropdown to select which course is to be completed prior to allowing enrollment in the next course is limited to a list of 100 courses.  Our Moodle site has nearly three times that many courses. Can the list be made to show all courses within the site?

### To Reproduce
Complete and precise steps to reproduce the behavior:
1. Go to 'Click on course'
2. Click on 'Enrolled Users'
3. Click on 'Enrolled Users drop down list'
4. Select Enrollment Methods
5. Click on 'Add method'
6. Scroll down to 'Course Completed enrolment'
7. Scroll down to 'Search'
8. Only 100 courses are available to scroll.  Not all of my courses are showing up in the search list.

## Expected behavior
I expect to see all of the courses available in the Moodle site to choose from.

## Additional context
Please provide any relevant information about your setup. This is important in case the issue is not reproducible, except under certain conditions.
- Moodle version 4.1.2
- plugin version v4.1.1
- php version 8.0.30

**Comment by ewallah** [comment]
Hello @maxmail 

THX for your report.

This plugin has no hard coded maximum number of courses to show, but limits the selection by [3 conditions](https://github.com/ewallah/moodle-enrol_coursecompleted/blob/main/lib.php#L326):
- onlywithcompletion: true, 
- multiple: false
- includefrontpage: false

Only courses who have completion enabled are listed as there is no point in creating an enrollment on course completion when it is impossible to complete this course.

Can you confirm that more than 100 courses have completion enabled?
