### ISSUE TITLE
No enrolstartdate is created if the option isn't ticked in the settings

### ISSUE THREAD

**Issue by turf212** [ewallah/moodle-enrol_coursecompleted#39]
## Describe the bug
In the observer.php file for the course completed event the code uses the enrolstartdate setting value for the enrol_user() function.  If this is unticked then no enrolstartdate is set for the user's enrolment when it should be set as the time the event is fired.

### To Reproduce
Set up a course enrolment based off of the completion of another course.  As a student complete this second course. In the first course the student will not have any start date set for their enrolment.

## Expected behavior
Start date should be set to either the startdate defined or the time the event was consumed by the observer.

## Additional context

Changing the observer to the following at line 49 fixes this issue

```
                    // Invalid courses are already detected when context is calculated.
                    if ($DB->record_exists('course', ['id' => $enrol->courseid])) {
                        if (empty($enrol->enrolstartdate)) {
                            $enrol->enrolstartdate = $event->timecreated;
                        }
                        if ($enrol->enrolperiod > 0) {
                            $enrol->enrolenddate = max(time(), $enrol->enrolstartdate) + $enrol->enrolperiod;
                        }
```

**Comment by ewallah** [comment]
THX for your clear and complete bug report.

One of these days your suggestion will be implemented.

**Comment by ewallah** [comment]
DONE.
