### ISSUE TITLE
Error occurs when courses which control the enrolment are deleted.

### ISSUE THREAD

**Issue by jjs105** [ewallah/moodle-enrol_coursecompleted#5]
When visiting a course that has been configured to base enrolment on completion of another course that has since be deleted a database error occurs.

This is because the code assumes that the queried course will always exist.  Suggestions for fix would be:

1. Change code in lib.php (line 45) to check result of course query and return 'unknown' string or similar
2. Add an event handler to the course deleted event which checks for and then deletes links to other courses that depend on i'rs completion for enrolment
3. Check for similar errors in the code base (I am not 100% familiar)

**Comment by ewallah** [comment]
THX for the report. I will try to fix this ASAP.

**Comment by ewallah** [comment]
Code fixed for 3.4 - 3.5 - 3.6

The plugin now checks if the course exist and a course deleted event was added.

The combination of this course deleted event and the use of the recycle bin has to be monitored and evaluated,
