### ISSUE TITLE
Different date for different versions?

### ISSUE THREAD

**Issue by Jarvil** [ewallah/moodle-enrol_coursecompleted#7]
Hello,

Would it be possible for you to change the date of the plugin for different version releases? This would help automated installations.

On:

https://moodle.org/plugins/pluginversions.php?plugin=enrol_coursecompleted

you have: 

3.6 (2019022300)Moodle 3.6
3.5 (2019022300)Moodle 3.5
3.4 (2019022300)Moodle 3.4

Every release has the same 2019022300 date which doesn't work with automation installation.

**Comment by ewallah** [comment]
Hello Jarvis,

can you explain this a bit more (MDL-????? or discussion forum)?

Each branch has a different release and a different version requires, and you ask me to provide a different version date?


Greetings,

**Comment by Jarvil** [comment]
Hello,

Please see this: https://github.com/CLAMP-IT/moodlegist/issues/3

**Comment by ewallah** [comment]
Fixed.
master (2019032500) Moodle maste
3.6 (2019032506)Moodle 3.6
3.5 (2019032505)Moodle 3.5
3.4 (2019032504)Moodle 3.4

**Comment by Jarvil** [comment]
Hello,

Thank you very much.
