### ISSUE TITLE
enrol_coursecompleted enrollment expiry action not working like in settings

### ISSUE THREAD

**Issue by will-bulluck** [ewallah/moodle-enrol_coursecompleted#8]
When setting the enrol_coursecompleted enrollment expiry action to unenroll from course, - Students are set to not current instead of being unenrolled

**Comment by ewallah** [comment]
Hello Will,

THX for the problem report.

This seems to be a tricky problem: because the plugin does not override the enrol_user, update_user_enrol or unenrol_user functions, everything is handled by standard Moodle functions. So the problem will be related to the allow_unenrol and allow_manage permissions.

Can you send me sample log entries for your expiry events?

**Comment by ewallah** [comment]
Hello Will,

In real life I cannot reproduce your problem, so I changed the phpunit testing to check the behaviour:https://github.com/ewallah/moodle-enrol_coursecompleted/commit/2589a5a4e536a307edcb445a506107847ac34b1a#diff-2dd3602d8aec94aced4eeacc7db7a9e6

I created 3 new courses.  When users complete course 3 they will be enrolled into course 1 for 3 seconds, and into course 2 for 6 seconds. When course 3 is marked completed, the student is automatically enrolled into course 1 and course 2. After 3 seconds, the user is still enrolled into course 1, but not active.  After switching the expiredaction to ENROL_EXT_REMOVED_UNENROL and waiting another 3 seconds, the user is completely unenrolled from course 2.

Are you sure that the default expiry action was REMOVED_UNENROL the moment the expiry happened?

**Comment by will-bulluck** [comment]
Good morning and thanks for the quick response,

Here is the setting for the plugin:
https://drive.google.com/file/d/1xY-Lt5Dx9aVINwzECnY5LrUMeFN5md_y/view?usp=sharing

The moment the expiry happens the student status goes from Active to Not current.

**Comment by ewallah** [comment]
Are you sure that the default expiry action was REMOVED_UNENROL the moment the expiry happened?

**Comment by will-bulluck** [comment]
Yes, the default expiry action has always been to do that.

**Comment by ewallah** [comment]
I was able to reproduce the error in Behat.

**Comment by will-bulluck** [comment]
Good afternoon,

I just wanted to check in with you and see how progress is going?

Will

**Comment by ewallah** [comment]
Hello Will,

I provided a solution in the branches master and MOODLE_36_STABLE so now everything can be tested. But I do not feel 100% sure yet this is the most simple and complete workaround for this bug.

Feel free to download the version from github and see if everything is working like it should.

R

**Comment by will-bulluck** [comment]
R,

Good morning. Will the MOODLE_36_STABLE branch work with Moodle 35?

Will

**Comment by ewallah** [comment]
Hello WIl,

one more question: do you have other enrolment plugins installed? And do they correctly follow the expiry action?

R

**Comment by ewallah** [comment]
The MOODLE_36_STABLE branch will **not** work in 3.5 (the cache cleaning mechanism changed in Moodle).

R

**Comment by will-bulluck** [comment]
Other users are enrolled via manual enrollments and that is working fine.

Will

**Comment by will-bulluck** [comment]
Can I ask you to make it available for Moodle 35?

**Comment by will-bulluck** [comment]
Good morning,

Is there any update on this?

Just checking in,

Will

**Comment by ewallah** [comment]
Fixed

**Comment by LWaechter** [comment]
This is available for 35 now as well?
